#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muong_Thanh_Hotel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ProjectData")]
	public partial class projectDatadbmlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertdanhSachKhachHang(danhSachKhachHang instance);
    partial void UpdatedanhSachKhachHang(danhSachKhachHang instance);
    partial void DeletedanhSachKhachHang(danhSachKhachHang instance);
    partial void InsertdanhSachPhong(danhSachPhong instance);
    partial void UpdatedanhSachPhong(danhSachPhong instance);
    partial void DeletedanhSachPhong(danhSachPhong instance);
    partial void InsertdanhSachYeuCau(danhSachYeuCau instance);
    partial void UpdatedanhSachYeuCau(danhSachYeuCau instance);
    partial void DeletedanhSachYeuCau(danhSachYeuCau instance);
    #endregion
		
		public projectDatadbmlDataContext() : 
				base(global::Muong_Thanh_Hotel.Properties.Settings.Default.ProjectDataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public projectDatadbmlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public projectDatadbmlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public projectDatadbmlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public projectDatadbmlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<danhSachKhachHang> danhSachKhachHangs
		{
			get
			{
				return this.GetTable<danhSachKhachHang>();
			}
		}
		
		public System.Data.Linq.Table<danhSachPhong> danhSachPhongs
		{
			get
			{
				return this.GetTable<danhSachPhong>();
			}
		}
		
		public System.Data.Linq.Table<danhSachYeuCau> danhSachYeuCaus
		{
			get
			{
				return this.GetTable<danhSachYeuCau>();
			}
		}
		
		public System.Data.Linq.Table<danhSachNhanVien> danhSachNhanViens
		{
			get
			{
				return this.GetTable<danhSachNhanVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.danhSachKhachHang")]
	public partial class danhSachKhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CCCD;
		
		private string _hoTen;
		
		private string _gioiTinh;
		
		private System.Nullable<int> _sdt;
		
		private string _diaChi;
		
		private string _quocTich;
		
		private string _ngaySinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCCCDChanging(int value);
    partial void OnCCCDChanged();
    partial void OnhoTenChanging(string value);
    partial void OnhoTenChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OnsdtChanging(System.Nullable<int> value);
    partial void OnsdtChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnquocTichChanging(string value);
    partial void OnquocTichChanged();
    partial void OnngaySinhChanging(string value);
    partial void OnngaySinhChanged();
    #endregion
		
		public danhSachKhachHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NChar(10)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this.OnhoTenChanging(value);
					this.SendPropertyChanging();
					this._hoTen = value;
					this.SendPropertyChanged("hoTen");
					this.OnhoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NChar(10)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Int")]
		public System.Nullable<int> sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NChar(10)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quocTich", DbType="NChar(10)")]
		public string quocTich
		{
			get
			{
				return this._quocTich;
			}
			set
			{
				if ((this._quocTich != value))
				{
					this.OnquocTichChanging(value);
					this.SendPropertyChanging();
					this._quocTich = value;
					this.SendPropertyChanged("quocTich");
					this.OnquocTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="NChar(10)")]
		public string ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.danhSachPhong")]
	public partial class danhSachPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _soPhong;
		
		private string _loaiPhong;
		
		private System.Nullable<int> _soTang;
		
		private System.Nullable<double> _gia;
		
		private string _trangThaiPhong;
		
		private string _loaiGiuong;
		
		private string _isAvailable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsoPhongChanging(int value);
    partial void OnsoPhongChanged();
    partial void OnloaiPhongChanging(string value);
    partial void OnloaiPhongChanged();
    partial void OnsoTangChanging(System.Nullable<int> value);
    partial void OnsoTangChanged();
    partial void OngiaChanging(System.Nullable<double> value);
    partial void OngiaChanged();
    partial void OntrangThaiPhongChanging(string value);
    partial void OntrangThaiPhongChanged();
    partial void OnloaiGiuongChanging(string value);
    partial void OnloaiGiuongChanged();
    partial void OnisAvailableChanging(string value);
    partial void OnisAvailableChanged();
    #endregion
		
		public danhSachPhong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soPhong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int soPhong
		{
			get
			{
				return this._soPhong;
			}
			set
			{
				if ((this._soPhong != value))
				{
					this.OnsoPhongChanging(value);
					this.SendPropertyChanging();
					this._soPhong = value;
					this.SendPropertyChanged("soPhong");
					this.OnsoPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiPhong", DbType="NVarChar(50)")]
		public string loaiPhong
		{
			get
			{
				return this._loaiPhong;
			}
			set
			{
				if ((this._loaiPhong != value))
				{
					this.OnloaiPhongChanging(value);
					this.SendPropertyChanging();
					this._loaiPhong = value;
					this.SendPropertyChanged("loaiPhong");
					this.OnloaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTang", DbType="Int")]
		public System.Nullable<int> soTang
		{
			get
			{
				return this._soTang;
			}
			set
			{
				if ((this._soTang != value))
				{
					this.OnsoTangChanging(value);
					this.SendPropertyChanging();
					this._soTang = value;
					this.SendPropertyChanged("soTang");
					this.OnsoTangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Float")]
		public System.Nullable<double> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThaiPhong", DbType="NChar(10)")]
		public string trangThaiPhong
		{
			get
			{
				return this._trangThaiPhong;
			}
			set
			{
				if ((this._trangThaiPhong != value))
				{
					this.OntrangThaiPhongChanging(value);
					this.SendPropertyChanging();
					this._trangThaiPhong = value;
					this.SendPropertyChanged("trangThaiPhong");
					this.OntrangThaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiGiuong", DbType="NChar(10)")]
		public string loaiGiuong
		{
			get
			{
				return this._loaiGiuong;
			}
			set
			{
				if ((this._loaiGiuong != value))
				{
					this.OnloaiGiuongChanging(value);
					this.SendPropertyChanging();
					this._loaiGiuong = value;
					this.SendPropertyChanged("loaiGiuong");
					this.OnloaiGiuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isAvailable", DbType="NChar(10)")]
		public string isAvailable
		{
			get
			{
				return this._isAvailable;
			}
			set
			{
				if ((this._isAvailable != value))
				{
					this.OnisAvailableChanging(value);
					this.SendPropertyChanging();
					this._isAvailable = value;
					this.SendPropertyChanged("isAvailable");
					this.OnisAvailableChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.danhSachYeuCau")]
	public partial class danhSachYeuCau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maYeuCau;
		
		private System.Nullable<int> _CCCD;
		
		private System.Nullable<int> _soPhong;
		
		private string _maDichVu;
		
		private string _trangThaiXuLi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaYeuCauChanging(int value);
    partial void OnmaYeuCauChanged();
    partial void OnCCCDChanging(System.Nullable<int> value);
    partial void OnCCCDChanged();
    partial void OnsoPhongChanging(System.Nullable<int> value);
    partial void OnsoPhongChanged();
    partial void OnmaDichVuChanging(string value);
    partial void OnmaDichVuChanged();
    partial void OntrangThaiXuLiChanging(string value);
    partial void OntrangThaiXuLiChanged();
    #endregion
		
		public danhSachYeuCau()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maYeuCau", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maYeuCau
		{
			get
			{
				return this._maYeuCau;
			}
			set
			{
				if ((this._maYeuCau != value))
				{
					this.OnmaYeuCauChanging(value);
					this.SendPropertyChanging();
					this._maYeuCau = value;
					this.SendPropertyChanged("maYeuCau");
					this.OnmaYeuCauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="Int")]
		public System.Nullable<int> CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soPhong", DbType="Int")]
		public System.Nullable<int> soPhong
		{
			get
			{
				return this._soPhong;
			}
			set
			{
				if ((this._soPhong != value))
				{
					this.OnsoPhongChanging(value);
					this.SendPropertyChanging();
					this._soPhong = value;
					this.SendPropertyChanged("soPhong");
					this.OnsoPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDichVu", DbType="NVarChar(10)")]
		public string maDichVu
		{
			get
			{
				return this._maDichVu;
			}
			set
			{
				if ((this._maDichVu != value))
				{
					this.OnmaDichVuChanging(value);
					this.SendPropertyChanging();
					this._maDichVu = value;
					this.SendPropertyChanged("maDichVu");
					this.OnmaDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThaiXuLi", DbType="NVarChar(10)")]
		public string trangThaiXuLi
		{
			get
			{
				return this._trangThaiXuLi;
			}
			set
			{
				if ((this._trangThaiXuLi != value))
				{
					this.OntrangThaiXuLiChanging(value);
					this.SendPropertyChanging();
					this._trangThaiXuLi = value;
					this.SendPropertyChanged("trangThaiXuLi");
					this.OntrangThaiXuLiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.danhSachNhanVien")]
	public partial class danhSachNhanVien
	{
		
		private System.Nullable<int> _CCCD;
		
		private string _hoTen;
		
		private string _gioiTinh;
		
		private string _ngaySInh;
		
		private System.Nullable<int> _sdt;
		
		private string _diaChi;
		
		private string _quocTich;
		
		private System.Nullable<double> _luong;
		
		private string _hireDate;
		
		public danhSachNhanVien()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="Int")]
		public System.Nullable<int> CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this._CCCD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NChar(10)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this._hoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NChar(10)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this._gioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySInh", DbType="NChar(10)")]
		public string ngaySInh
		{
			get
			{
				return this._ngaySInh;
			}
			set
			{
				if ((this._ngaySInh != value))
				{
					this._ngaySInh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Int")]
		public System.Nullable<int> sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this._sdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NChar(10)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this._diaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quocTich", DbType="NChar(10)")]
		public string quocTich
		{
			get
			{
				return this._quocTich;
			}
			set
			{
				if ((this._quocTich != value))
				{
					this._quocTich = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luong", DbType="Float")]
		public System.Nullable<double> luong
		{
			get
			{
				return this._luong;
			}
			set
			{
				if ((this._luong != value))
				{
					this._luong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hireDate", DbType="NChar(10)")]
		public string hireDate
		{
			get
			{
				return this._hireDate;
			}
			set
			{
				if ((this._hireDate != value))
				{
					this._hireDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
